name: k6 BMI

on:
  workflow_dispatch:

jobs:
  k6_load_test:
    runs-on: ubuntu-latest

    env:
      BASE_URL: "https://bpcalc-dqdzd2c5e9h0cvg3.francecentral-01.azurewebsites.net"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull k6 Docker image
        run: docker pull grafana/k6

      - name: Run k6 load test
        run: |
          docker run --rm \
            -e BASE_URL="${BASE_URL}" \
            -v "${{ github.workspace }}/k6:/scripts:ro" \
            grafana/k6 run /scripts/perf1.js
